apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hangman
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mircoporetti/hangman
  ref:
    branch: main
